name: 'Project Lint'
description: 'Run linting checks for the project'

runs:
  using: 'composite'
  steps:
    - name: Lint with flake8
      run: |
        flake8 scraper quotes --max-line-length=88 --extend-ignore=E203,W503,E501
      shell: bash

    - name: Check formatting with black
      run: |
        black --check scraper quotes tests
      shell: bash

    - name: Check import sorting with isort
      run: |
        isort --check-only --profile black scraper quotes tests
      shell: bash

    - name: Type check with mypy
      run: |
        mypy scraper quotes --ignore-missing-imports
      shell: bash
