name: 'Project Setup'
description: 'Set up project environment and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.14
      # https://github.com/actions/setup-python/releases - Latest: v5.3.0 (2024-10-24)
      # https://www.python.org/downloads/windows/ - Python 3.14 required
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - id: cache-pip
      name: Cache pip packages
      # https://github.com/actions/cache/releases - Latest: v4.1.2 (2024-11-11)
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pip/wheels
          %LOCALAPPDATA%\\pip\\Cache
          %LOCALAPPDATA%\\pip\\Cache\\wheels
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - id: cache-pre-commit
      name: Cache pre-commit hooks
      # https://github.com/actions/cache/releases - Latest: v4.1.2 (2024-11-11)
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
          %LOCALAPPDATA%\\pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('pyproject.toml', '.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      shell: bash

    - name: Show cache status
      run: |
        echo "pip cache hit: ${{ steps.cache-pip.outputs.cache-hit }}"
        echo "pre-commit cache hit: ${{ steps.cache-pre-commit.outputs.cache-hit }}"
      shell: bash
