name: 'Project Test'
description: 'Run tests and upload coverage reports'

runs:
  using: 'composite'
  steps:
    - name: Run tests with pytest
      run: |
        pytest --cov=scraper --cov=quotes --cov-report=term-missing --cov-report=xml --cov-report=html --cov-report=json --cov-report=lcov --cov-fail-under=95
      shell: bash

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          htmlcov/
          coverage.xml
          coverage.json
          coverage.lcov
        retention-days: 1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
